from crewai import Agent, Task, Crew
from dotenv import load_dotenv
from agents.log_analyzer import analyze_log
from agents.web_search import find_fix
from tools.github_tool import create_github_issue
import os

load_dotenv()

def run_incident_resolver(log_content: str) -> dict:
    """Main function that orchestrates all agents."""
    
    results = {
        "status": "started",
        "log_analysis": None,
        "fix": None,
        "github_issue": None,
        "self_correction": False
    }
    
    # Step 1 — Analyze the log
    print("\n🔍 Step 1: Analyzing logs...")
    log_analysis = analyze_log(log_content)
    results["log_analysis"] = log_analysis
    print(f"✅ Error detected: {log_analysis.get('error', 'Unknown')}")
    print(f"✅ Severity: {log_analysis.get('severity', 'Unknown')}")
    print(f"✅ Responsible Role: {log_analysis.get('role', 'Unknown')}")
    
    # Step 2 — Search for fix
    print("\n🔎 Step 2: Searching for fixes...")
    error_message = log_analysis.get("error", "")
    fix = find_fix(error_message)
    results["fix"] = fix
    print(f"✅ Fix found with confidence: {fix.get('confidence', 'Unknown')}")
    
    # Step 3 — Self correction if confidence is low
    if fix.get("confidence", "").lower() == "low":
        print("\n⚠️ Low confidence fix. Trying self-correction...")
        results["self_correction"] = True
        summary = log_analysis.get("summary", "")
        fix = find_fix(summary)
        results["fix"] = fix
        print(f"✅ Self-corrected fix confidence: {fix.get('confidence', 'Unknown')}")
    
    # Step 4 — Create GitHub Issue
    print("\n📝 Step 3: Creating GitHub Issue...")
    
    issue_title = f"Incident: {log_analysis.get('error', 'Unknown Error')}"
    
    issue_body = f"""
## 🔍 Log Analysis
- **Error:** {log_analysis.get('error', 'N/A')}
- **File:** {log_analysis.get('file', 'N/A')}
- **Summary:** {log_analysis.get('summary', 'N/A')}
- **Responsible Team:** {log_analysis.get('role', 'N/A')}

## 🛠️ Proposed Fix
- **Primary Fix:** {fix.get('fix1', 'N/A')}
- **Backup Fix:** {fix.get('fix2', 'N/A')}
- **Confidence:** {fix.get('confidence', 'N/A')}

## 📋 Steps to Fix
{fix.get('steps', 'N/A')}

## 🤖 Agent Notes
- Self-correction triggered: {results['self_correction']}
- Auto-generated by DevOps Incident Resolver Agent
    """
    
    github_result = create_github_issue(
        title=issue_title,
        body=issue_body,
        severity=log_analysis.get("severity", "High")
    )
    
    results["github_issue"] = github_result
    results["status"] = "completed"
    
    print(f"\n{github_result}")
    
    return results