import os
from github import Github
from dotenv import load_dotenv

load_dotenv()

def create_github_issue(title: str, body: str, severity: str) -> str:
    """Create a GitHub issue with the error details and proposed fix."""
    try:
        g = Github(os.getenv("GITHUB_TOKEN"))
        repo = g.get_repo(os.getenv("GITHUB_REPO"))
        
        # Add severity label styling in the body
        full_body = f"""
## 🚨 Severity: {severity}

## 📋 Error Details
{body}

## 🤖 Auto-generated by DevOps Incident Resolver Agent
        """
        
        issue = repo.create_issue(
            title=f"[{severity}] {title}",
            body=full_body
        )
        
        return f"✅ GitHub Issue created: {issue.html_url}"
    
    except Exception as e:
        return f"❌ Failed to create issue: {str(e)}"